<?php
/**
 * @file
 * Code for the Stewardship feature.
 */

include_once 'stewardship.features.inc';

/**
 * Implements hook_menu().
 */

function stewardship_menu() {
  $items = array();
  $items['admin/content/giving'] = array(
    'title' => 'Giving',
    'description' => 'Adjust Giving page options',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('stewardship_form'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_LOCAL_TASK,
  );
  $items['giving'] = array(
    'title' => 'Giving & Stewardship',
    'page callback' => 'stewardship_page',
    'access callback' => TRUE,
  );
  return $items;
}

/* admin form for stewarship */

function stewardship_form($form,&$form_state) {
  $message = variable_get('stewardship_message','');
  if (!isset($message['value'])) {
    $message['value'] = '';
  }
  $form['stewardship_video'] = array(
      '#title' => t('Stewardship Video'),
      '#description' => 'Video to show in introduction area',
      '#type' => 'media',
      '#tree' => TRUE,
      '#default_value' => variable_get('stewardship_video', ''),
      '#media_options' => array(
        'global' => array(
          'disabledPlugins' => array('upload','library'),
          'schemes' => array(
            'youtube' => 'youtube',
          ),
          'file_extensions' => '',
          'max_filesize' => '10 MB',
          'uri_scheme' => 'youtube',
        ),
      ),
  );
  $form['stewardship_message'] = array(
      '#type' => 'text_format',
      '#title' => 'Message',
      '#default_value' => $message['value'],
  );
  $ways = variable_get('stewardship_ways','');
  if (!isset($ways['value'])) {
    $ways['value'] = '';
  }
  $stewardships = stewardship_query_stories(TRUE);
  $form['stewardship_add_link'] = array(
    '#type' => 'item',
    '#markup' => l("+ Add giving story","node/add/stewardship-story"),
    '#title' => "Stewardship Stories",
    '#prefix' => "<br /><br />",
  );
  $form = array_merge($form,stewardship_build_stewardship_table($stewardships));
  $form['stewardship_donor_photos'] = array(
    '#type' => 'checkbox',
    '#title' => 'Show donor story photos on main giving page',
    '#default_value' => variable_get('stewardship_donor_photos',1),
  );
  $form['stewardship_donor_videos'] = array(
    '#type' => 'checkbox',
    '#title' => 'Show donor story videos on main giving page',
    '#default_value' => variable_get('stewardship_donor_videos',0),
  );
  $form['#submit'] = array('stewardship_form_submit');
  $form['stewardship_ways'] = array(
      '#type' => 'text_format',
      '#title' => 'Ways of Giving',
      '#default_value' => $ways['value'],
  );
  return system_settings_form($form);
}

/* builds stewardship page */

function stewardship_page() {
  $message = variable_get("stewardship_message","");
  $stories = stewardship_query_stories();
  $ways = variable_get("stewardship_ways","");
  return theme("stewardship",array(
    'message' => $message,
    'stories' => $stories,
    'ways' => $ways,
  ));
}

/* entity query for donor stories */

function stewardship_query_stories($unpublished = FALSE) {
  $query = new EntityFieldQuery();
  $query->entityCondition('entity_type', 'node')
    ->entityCondition('bundle', 'stewardship_story')
    ->fieldOrderBy('field_stewardship_weight', 'value', 'ASC')
    ->propertyOrderBy('title','ASC');
  if (!$unpublished) {
    $query->propertyCondition('status', 1);
  }
  $result = $query->execute();
  $stories = array('nodes' => array(), 'pager' => '');
  if (isset($result['node'])) {
    $stories_nids = array_keys($result['node']);
    $stories = array('nodes'=>entity_load('node', $stories_nids));
  }
  return $stories;
}

/****************************
Implementation of hook_theme()
****************************/

function stewardship_theme() {
  return array(
    'stewardship' => array(
      'variables' => array('message'=>NULL,'stories'=>NULL,'ways'=>NULL),
      'template' => 'theme/stewardship',
    ),
    'stewardship_table_drag_components' => array(
      'render element' => 'element'
    ),
  );
}

/* helper function for building stewardship admin table */

function stewardship_build_stewardship_table($stewardships) {
  $stewardship_table = array();
  $stewardship_table['stewardship_table_drag_attributes'] = array(
    '#prefix' => '<div id="stewardship-attributes">',
    '#suffix' => '</div>',
    '#tree' => TRUE,
    '#theme' => 'stewardship_table_drag_components',
  );
  $count = 0;
  foreach ($stewardships['nodes'] as $stewardship) {
    $count++;
    $stewardship_table['stewardship_table_drag_attributes'][$count] = array();
    $actions = "";
    if (node_access("update",$stewardship)) {
      $actions .= l("edit","node/".$stewardship->nid."/edit")." ";
    }
    if (node_access("delete",$stewardship)) {
      $actions .= l("delete","node/".$stewardship->nid."/delete");
    }
    $stewardship_table['stewardship_table_drag_attributes'][$count]['nid'] = array(
      '#type' => 'hidden',
      '#value' => $stewardship->nid,
    );
    if (isset($stewardship->field_stewardship_featured_image['und'][0])) {
      $stewardship_table['stewardship_table_drag_attributes'][$count]['image'] = array(
       '#type' => 'markup',
       '#markup' => theme_image_style(array('path' => $stewardship->field_stewardship_featured_image['und'][0]['uri'], 'style_name' => 'stewardship_admin','width'=>NULL,'height'=>NULL)),
      );
    }
    $stewardship_table['stewardship_table_drag_attributes'][$count]['title'] = array(
      '#type' => 'markup',
      '#markup' => $stewardship->title,
    );
    $stewardship_table['stewardship_table_drag_attributes'][$count]['text'] = array(
      '#type' => 'markup',
      '#markup' =>      $stewardship->body['und'][0]['summary'],
    );
    $stewardship_table['stewardship_table_drag_attributes'][$count]['status'] = array(
      '#type' => 'checkbox',
      '#default_value' => $stewardship->status,
      '#attributes' => array('class' => array('status')),
    );
    $stewardship_table['stewardship_table_drag_attributes'][$count]['actions'] = array(
      '#type' => 'markup',
      '#markup' =>      $actions,
    );
    if (isset($stewardship->field_stewardship_weight['und'])) {
      $position = $stewardship->field_stewardship_weight['und'][0]['value'];
    }
    else {
      $position = $count;
    }
    $stewardship_table['stewardship_table_drag_attributes'][$count]['weight'] = array(
      '#type' => 'textfield',
      '#default_value' => $position,
      '#size' => 3,
      '#attributes' => array('class' => array('item-row-weight')),
    );
  }
  return $stewardship_table;
}

/* helper function for stewardshiop table */

function theme_stewardship_table_drag_components($vars) {
  $element = $vars['element'];
  drupal_add_tabledrag('stewardship_table', 'order', 'sibling', 'item-row-weight');
  $header = array(
    'title' => t('Title'),
    'image' => t('Image'),
    'text' => t('Text'),
    'status' => t('Published'),
    'actions' => t('Actions'),
    'weight' => t('Weight'),
  );
  $rows = array();
  foreach (element_children($element) as $key) {
    $row = array();
    $row['data'] = array();
    foreach ($header as $fieldname => $title) {
      $row['data'][] = drupal_render($element[$key][$fieldname]);
      $row['class'] = array('draggable');
    }
    $rows[] = $row;  
  }
  return theme('table', array(
    'header' => $header,
    'rows' => $rows,
    'attributes' => array('id' => 'stewardship_table'),   
  ));
}

/* stewardship form submission hook to save node weight/status */

function stewardship_form_submit($form, &$form_state) {
  foreach ($form_state['values']["stewardship_table_drag_attributes"] as $key => $stewardship) {
    $node = node_load($stewardship['nid']);
    $node->field_stewardship_weight['und'] = array(
      '0' => array(
         'value' => $stewardship['weight'],
       ),
    );
    $node->status = $stewardship['status'];
    node_save($node);
  }
}

