<?php

/* calls init function to always disable undesirable modules
   and set homepage to this module's content */

function interface_adjustments_init() {
  variable_set("site_frontpage","home");
  if (module_exists("dashboard")) {
    module_disable(array("dashboard"));
    drupal_set_message("Dashboard module disabled.");
    menu_rebuild();
    cache_clear_all();
  }
  if (module_exists("shortcut")) {
    module_disable(array("shortcut"));
    drupal_set_message("Shortcut module disabled.");
    menu_rebuild();
    cache_clear_all();
  }
  if (module_exists("comment")) {
    module_disable(array("comment"));
    drupal_set_message("Comment module disabled.");
    menu_rebuild();
    cache_clear_all();
  }
  if (!module_exists("color")) {
    module_enable(array("color"));
    drupal_set_message("Color module enabled.");
    menu_rebuild();
    cache_clear_all();
  }
  if (module_exists("search")) {
    module_disable(array("search"));
    drupal_set_message("Search module disabled.");
    menu_rebuild();
    cache_clear_all();
  }
}

// Removes the js that hides the summary field in node add form.

function interface_adjustments_js_alter(&$javascript) {
  unset($javascript['modules/field/modules/text/text.js']);
}

function interface_adjustments_form_alter(&$form, &$form_state, $form_id) {
  $test = "_node_form";
  if (substr_compare($form_id, $test, -strlen($test), strlen($test)) === 0) {
    $form['options']['#weight'] = -1000;
    $form['options']['sticky']['#title'] = "Featured at top of lists";
    unset($form['options']['promote']);
  }
  if ($form_id == "node_admin_content") {
    unset($form['filter']['filters']['status']['filters']['status']['#options']['promote-1']);
    unset($form['filter']['filters']['status']['filters']['status']['#options']['promote-0']);
    $form['filter']['filters']['status']['filters']['status']['#options']['sticky-1'] = "featured";
    $form['filter']['filters']['status']['filters']['status']['#options']['sticky-0'] = "not featured";
    unset($form['admin']['options']['operation']['#options']['promote']);
    unset($form['admin']['options']['operation']['#options']['demote']);
    $form['admin']['options']['operation']['#options']['sticky'] = "Feature selected content";
    $form['admin']['options']['operation']['#options']['unsticky'] = "Unfeature selected content";
  }
}

