<?php

/* calls init function to always disable undesirable modules
   and set homepage to this module's content */

function interface_adjustments_init() {
  variable_set("site_frontpage","home");
  if (module_exists("dashboard")) {
    module_disable(array("dashboard"));
    drupal_set_message("Dashboard module disabled.");
    menu_rebuild();
    cache_clear_all();
  }
  if (module_exists("shortcut")) {
    module_disable(array("shortcut"));
    drupal_set_message("Shortcut module disabled.");
    menu_rebuild();
    cache_clear_all();
  }
  if (module_exists("comment")) {
    module_disable(array("comment"));
    drupal_set_message("Comment module disabled.");
    menu_rebuild();
    cache_clear_all();
  }
  if (module_exists("color")) {
    module_disable(array("color"));
    drupal_set_message("Color module disabled.");
    menu_rebuild();
    cache_clear_all();
  }
  if (module_exists("dblog")) {
    module_disable(array("dblog"));
    drupal_set_message("Database logging module disabled.");
    menu_rebuild();
    cache_clear_all();
  }
  if (module_exists("search")) {
    module_disable(array("search"));
    drupal_set_message("Search module disabled.");
    menu_rebuild();
    cache_clear_all();
  }
}

// Removes the js that hides the summary field in node add form.

function interface_adjustments_js_alter(&$javascript) {
  unset($javascript['modules/field/modules/text/text.js']);
}
