<?php

/* calls init function to always disable undesirable modules
   and set homepage to this module's content */

function interface_adjustments_init() {
  variable_set("site_frontpage","home");
  if (module_exists("dashboard")) {
    module_disable(array("dashboard"));
    drupal_set_message("Dashboard module disabled.");
    menu_rebuild();
    cache_clear_all();
  }
  if (module_exists("shortcut")) {
    module_disable(array("shortcut"));
    drupal_set_message("Shortcut module disabled.");
    menu_rebuild();
    cache_clear_all();
  }
  if (module_exists("comment")) {
    module_disable(array("comment"));
    drupal_set_message("Comment module disabled.");
    menu_rebuild();
    cache_clear_all();
  }
  if (!module_exists("color")) {
    module_enable(array("color"));
    drupal_set_message("Color module enabled.");
    menu_rebuild();
    cache_clear_all();
  }
  if (module_exists("search")) {
    module_disable(array("search"));
    drupal_set_message("Search module disabled.");
    menu_rebuild();
    cache_clear_all();
  }
}

// Removes the js that hides the summary field in node add form.

function interface_adjustments_js_alter(&$javascript) {
  unset($javascript['modules/field/modules/text/text.js']);
}

function interface_adjustments_form_alter(&$form, &$form_state, $form_id) {
  $test = "_node_form";
  if (substr_compare($form_id, $test, -strlen($test), strlen($test)) === 0) {
    $form['options']['#weight'] = -1000;
    $form['options']['sticky']['#title'] = "Featured at top of lists";
    unset($form['options']['promote']);
  }
  if ($form_id == "node_admin_content") {
    unset($form['filter']['filters']['status']['filters']['status']['#options']['promote-1']);
    unset($form['filter']['filters']['status']['filters']['status']['#options']['promote-0']);
    $form['filter']['filters']['status']['filters']['status']['#options']['sticky-1'] = "featured";
    $form['filter']['filters']['status']['filters']['status']['#options']['sticky-0'] = "not featured";
    unset($form['admin']['options']['operation']['#options']['promote']);
    unset($form['admin']['options']['operation']['#options']['demote']);
    $form['admin']['options']['operation']['#options']['sticky'] = "Feature selected content";
    $form['admin']['options']['operation']['#options']['unsticky'] = "Unfeature selected content";
  }
}

function interface_adjustments_menu() {
  $items = array();
  $items['admin/config/development/initialize'] = array(
    'title' => 'Initialize Website',
    'description' => 'Flush all content from the website.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('interface_adjustments_initialize_form'),
    'access arguments' => array('administer site configuration'),
  );
  return $items;
}

function interface_adjustments_initialize_form($form,&$form_state) {
  $form['understand'] = array(
    '#type' => 'checkbox',
    '#title' => 'Yes, I understand this will completely erase my website content.',
    );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Destroy my website!',
    );
  $form['#submit'] = array('interface_adjustments_initialize_form_submit');
  return $form;
}

function interface_adjustments_initialize_form_submit(&$form_state) {
 if ($form_state['understand']['#checked']) {
   $node_query = new EntityFieldQuery();
   $node_query->entityCondition('entity_type', 'node');
   $node_result = $node_query->execute();
   if (isset($node_result['node'])) {
     $nids = array_keys($node_result['node']);
     foreach ($nids as $nid) {
       node_delete($nid);
     }
   }
     drupal_set_message("All nodes deleted.");
   $user_query = new EntityFieldQuery();
   $user_query->entityCondition('entity_type', 'user');
   $user_result = $user_query->execute();
   if (isset($user_result['user'])) {
     $uids = array_keys($user_result['user']);
     foreach ($uids as $uid) {
       if ($uid <> 1 && $uid <> 0) {
         user_delete($uid);
       }
     }
   }
     drupal_set_message("All users deleted.");
   $file_query = new EntityFieldQuery();
   $file_query->entityCondition('entity_type', 'file');
   $file_result = $file_query->execute();
   if (isset($file_result['file'])) {
     $fids = array_keys($file_result['file']);
     foreach ($fids as $fid) {
       $file = file_load($fid);
       drupal_set_message($fid);
       file_delete($file);
     }
   }
   drupal_set_message("All files deleted.");
 }
 flush_variables("front_page_");
 flush_variables("sidebar_");
 flush_variables("service_times");
 flush_variables("contact_us");
 flush_variables("stewardship_");
 flush_variables("site_name");
 flush_variables("cc_");
 flush_variables("theme_ccp_settings");
 drupal_set_message("All variables flushed.");
 module_disable(array("constant_contact"));
 drupal_set_message("Constant contact disabled");
 cache_clear_all();
}

function flush_variables($name) {
  $result = db_select('variable', 'v')
    ->fields('v',array('name'))
    ->condition('name',$name."%",'LIKE')
    ->execute();
  while ($record = $result->fetchField()) {
    variable_del($record);
  }
}
