<?php

/**
 * Implements hook_init().
 */

function sidebar_init() {
  drupal_add_js('http://maps.google.com/maps/api/js?sensor=false&amp;language=en','external');
}

/**
 * Implements hook_menu().
 */

function sidebar_menu() {
  $items = array();
  $items['admin/sidebar'] = array(
    'title' => 'Sidebar',
    'description' => 'Sidebar customization',
    'position' => 'left',
    'weight' => -9,
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('administer site configuration'),
    'file' => 'system.admin.inc',
    'file path' => drupal_get_path('module', 'system'),
  );
  $items['admin/sidebar/map'] = array(
    'title' => 'Sidebar map',
    'description' => 'Adjust sidebar map',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('sidebar_map_form'),
    'access arguments' => array('administer site configuration'),
  );
  $items['admin/sidebar/times'] = array(
    'title' => 'Service times',
    'description' => 'Adjust sidebar service times',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('sidebar_service_form'),
    'access arguments' => array('administer site configuration'),
  );
  $items['admin/sidebar/welcome'] = array(
    'title' => 'Welcome Packet',
    'description' => 'Adjust welcome packet title and text',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('sidebar_welcome_form'),
    'access arguments' => array('administer site configuration'),
  );
  $items['admin/sidebar/contact'] = array(
    'title' => 'Contact us',
    'description' => 'Adjust sidebar "Contact us" text',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('sidebar_contact_form'),
    'access arguments' => array('administer site configuration'),
  );
  $items['admin/sidebar/events'] = array(
    'title' => 'Upcoming Events',
    'description' => 'Adjust "Upcoming Events" text',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('sidebar_admin_events_form'),
    'access arguments' => array('administer site configuration'),
  );
  $items['upcoming-events'] = array(
    'title' => 'Upcoming Events',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('sidebar_upcoming_events_form'),
    'access callback' => TRUE,
  );
  return $items;
}

/* admin form for sidebar map settings */

function sidebar_map_form() {
  $form = array();
  $form['sidebar_map_address'] = array(
    '#type' => 'textarea',
    '#title' => 'Church address',
    '#description' => 'Used for sidebar map',
    '#default_value' => variable_get('sidebar_map_address',''),
  );
  $form['sidebar_map_external_url'] = array(
    '#type' => 'textfield',
    '#title' => 'URL to external map (Google, Mapquest, etc.)',
    '#description' => 'Used for link to external map',
    '#default_value' => variable_get('sidebar_map_external_url',''),
  );
  return system_settings_form($form);
}

/* admin form for sidebar events settings */

function sidebar_admin_events_form($form,&$form_state) {
  $form['sidebar_events_welcome'] = array(
    '#type' => 'select',
    '#title' => 'Display in Welcome Packet block',
    '#options' => array(
      'false' => "False",
      'true' => "True",
    ),
    '#default_value' => variable_get('sidebar_events_welcome','false'),
  );
  $form['sidebar_events_pref'] = array(
    '#type' => 'select',
    '#title' => 'Preferred Events Type',
    '#options' => array(
      'builtin' => 'Built-in events manager',
      'external' => 'External, e.g. Google Calendar plugin',
    ),
    '#default_value' => variable_get('sidebar_events_pref','builtin'),
  );
  $form['sidebar_events_block'] = array(
    '#type' => 'textarea',
    '#title' => 'External Events Block Code',
    '#description' => 'If using external code, paste iframe or other plugin code for the sidebar block.',
    '#default_value' => variable_get('sidebar_events_block',''),
  );
  $form['sidebar_events_page'] = array(
    '#type' => 'textarea',
    '#title' => 'External Events Page Code',
    '#description' => 'If using external code, paste iframe or other plugin code for the sidebar page.',
    '#default_value' => variable_get('sidebar_events_page',''),
  );
  return system_settings_form($form);
}



/* admin form for sidebar events settings */

function sidebar_upcoming_events_form($form, &$form_state) {
  $form['#method'] = "get";
/*
  $form['search'] = array(
    '#type' => 'fieldset',
    '#title' => 'Search Events',
    '#collapseable' => FALSE,
  );
  $form['search']['by_title'] = array(
    '#type' => 'textfield',
    '#title' => 'Title',
  );
  $form['search']['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Search',
  );
  $search = array();
  if (isset($_GET['by_title'])) {
    $form['search']['by_title']['#default_value'] = check_plain($_GET['by_title']);
    $search['by_title'] = check_plain($_GET['by_title']);
  }
 */
  $form['results'] = array(
    '#markup' => theme('sidebar_upcoming_events_page',array('events'=>sidebar_get_events(9,true,$search))),
  );
  return $form;
}

/* admin form for sidebar service times settings */

function sidebar_service_form() {
  $form = array();
  $service_times = variable_get('service_times',array('value'=>''));
  $service_times = $service_times['value'];
  $form['service_times'] = array(
    '#type' => 'text_format',
    '#title' => 'Service times text',
    '#default_value' => $service_times,
  );
  return system_settings_form($form);
}

/* admin form for sidebar welcome packet settings */

function sidebar_welcome_form() {
  $form = array();
  $form['sidebar_welcome'] = array(
    '#type' => 'textfield',
    '#title' => 'Title',
    '#default_value' => variable_get("sidebar_welcome","Welcome Packet"),
  );
  $welcome_text = variable_get('sidebar_welcome_text',array('value'=>''));
  $welcome_text = $welcome_text['value'];
  $form['sidebar_welcome_text'] = array(
    '#type' => 'text_format',
    '#title' => 'Welcome Packet text',
    '#default_value' => $welcome_text,
  );
  $form['sidebar_welcome_bulletins'] = array(
    '#type' => 'textfield',
    '#title' => 'Number of bulletins to display',
    '#default_value' => variable_get('sidebar_welcome_bulletins',1),
  );
  return system_settings_form($form);
}



/* admin form for sidebar contact settings */

function sidebar_contact_form() {
  $form = array();
  $contact_us = variable_get('contact_us',array('value'=>''));
  $contact_us = $contact_us['value'];
  $form['contact_us'] = array(
    '#type' => 'text_format',
    '#title' => 'Contact Us text',
    '#default_value' => $contact_us,
  );
  return system_settings_form($form);
}

/* hook_block_info() implementation */

function sidebar_block_info() {
  $blocks = array();
  $blocks['sidebar_map'] = array(
    'info' => t('Sidebar Chuch Map'),
    'status' => TRUE,
    'region' => 'sidebar_first',
  );
  $blocks['sidebar_services'] = array(
    'info' => t('Sidebar Church Services'),
    'status' => TRUE,
    'region' => 'sidebar_first',
  );
  $blocks['sidebar_contact'] = array(
    'info' => t('Sidebar Contact Us'),
    'status' => TRUE,
    'region' => 'sidebar_first',
  );
  $blocks['sidebar_events'] = array(
    'info' => t('Sidebar Upcoming Events'),
    'status' => TRUE,
    'region' => 'sidebar_first',
  );
  $blocks['sidebar_welcome'] = array(
    'info' => t('Sidebar Welcome Packet'),
    'status' => TRUE,
    'region' => 'sidebar_first',
  );
  return $blocks;
}

/* hook_block_view implementation */

function sidebar_block_view($delta = '') {
  switch ($delta) {
  case 'sidebar_map':
    $block['subject'] = "Join Us";
    $block['content'] = theme("sidebar_map",array('address'=>variable_get('sidebar_map_address',''),'external_url'=>variable_get('sidebar_map_external_url','')));
    break;
  case 'sidebar_services':
    $service_times = variable_get('service_times',array('value'=>''));
    $service_times = $service_times['value'];
    $block['subject'] = "Service Times";
    $block['content'] = check_markup($service_times,"full_html");
    break;
  case 'sidebar_contact':
    $contact_us = variable_get('contact_us',array('value'=>''));
    $contact_us = $contact_us['value'];
    $block['subject'] = "Contact Us";
    $block['content'] = check_markup($contact_us,"full_html");
    break;
  case 'sidebar_welcome':
    $block['subject'] = variable_get("sidebar_welcome","Welcome Packet");
    $block['content'] = theme("sidebar_welcome",array('calendars'=>sidebar_get_calendars(),'bulletins'=>sidebar_get_bulletins(variable_get("sidebar_welcome_bulletins",1)),'sermon'=>sidebar_get_sermon(),'newsletters'=>sidebar_get_newsletters(1),'letters'=>sidebar_get_letters(1),'events'=>sidebar_get_events(4),'announcements'=>sidebar_get_announcements(1)));
    break;
  case 'sidebar_events':
    $block['subject'] = "Upcoming Events";
    $block['content'] = theme("sidebar_upcoming_events",array('events'=>sidebar_get_events()));
    break;
  }
  return $block;
}

/* hook_contextual_links_view_alter() implementation */

function sidebar_contextual_links_view_alter(&$element, &$items) {
  if (isset($element['#element']['#block']) && $element['#element']['#block']->delta == "sidebar_services") {
    $element['#links'] = array();
    $element['#links']['edit-services'] = array(
      'title' => 'Edit service times',
      'href' => url('admin/sidebar/times', array('absolute' => TRUE)),
    );
  }
  if (isset($element['#element']['#block']) && $element['#element']['#block']->delta == "sidebar_map") {
    $element['#links'] = array();
    $element['#links']['edit-map'] = array(
      'title' => 'Edit map info',
      'href' => url('admin/sidebar/map', array('absolute' => TRUE)),
    );
  } 
  if (isset($element['#element']['#block']) && $element['#element']['#block']->delta == "sidebar_contact") {
    $element['#links'] = array();
    $element['#links']['edit-contact'] = array(
      'title' => 'Edit contact info',
      'href' => url('admin/sidebar/contact', array('absolute' => TRUE)),
    );
  }
}

/* entityquery for upcoming events nodes */

function sidebar_get_events($range = 4, $pager = false, $search = array()) {
  $query = new EntityFieldQuery();
  $query->entityCondition('entity_type', 'node')
    ->entityCondition('bundle', 'upcoming_event')
    ->propertyCondition('status', 1)
    ->fieldCondition('field_event_date','value',date('Y-m-d\TH:i:s'),">")
    ->propertyOrderBy('sticky','DESC')
    ->fieldOrderBy('field_event_date','value','ASC')
    ->propertyOrderBy('title','ASC');
  if (isset($search['by_title'])) {
    $query->propertyCondition('title',"%".$search['by_title']."%",'LIKE');
  }
  if (!$pager) {
    $query->range(0,$range);
  }
  else {
    $query->pager(10);
  }
  $result = $query->execute();
  $events = array('nodes' => array(), 'pager' => '');
  if (isset($result['node'])) {
    $events_nids = array_keys($result['node']);
    $events = array('nodes'=>entity_load('node', $events_nids));
    if ($pager) {
      $events['pager'] = theme('pager',$query->pager);
    }
  }
  return $events;
}

/* entityquery for upcoming calendars nodes */

function sidebar_get_calendars() {
  $query = new EntityFieldQuery();
  $query->entityCondition('entity_type', 'node')
    ->entityCondition('bundle', 'calendar')
    ->propertyCondition('status', 1)
    ->fieldCondition('field_calendar_date','value',date('Y-m-d\TH:i:s',mktime(0, 0, 0, date("n"), 1)),">=")
    ->fieldOrderBy('field_calendar_date','value','ASC')
    ->propertyOrderBy('title','ASC');
  $result = $query->execute();
  $calendars = array('nodes' => array());
  if (isset($result['node'])) {
    $calendars_nids = array_keys($result['node']);
    $calendars = array('nodes'=>entity_load('node', $calendars_nids));
  }
  else {
    return false;
  }
  return $calendars;
}

/* entityquery for upcoming calendars nodes */

function sidebar_get_bulletins($count = FALSE) {
  $query = new EntityFieldQuery();
  $query->entityCondition('entity_type', 'node')
    ->entityCondition('bundle', 'bulletin')
    ->propertyCondition('status', 1)
    ->fieldOrderBy('field_bulletin_date','value','DESC')
    ->propertyOrderBy('title','ASC');
  if ($count) {
    $query->range(0,$count);
  }
  $result = $query->execute();
  $bulletins = array('nodes' => array());
  if (isset($result['node'])) {
    $bulletin_nids = array_keys($result['node']);
    $bulletins = array('nodes'=>entity_load('node', $bulletin_nids));
  }
  else {
    return false;
  }
  return $bulletins;
}

/* entityquery for announcements nodes */

function sidebar_get_announcements($count = FALSE) {
  $query = new EntityFieldQuery();
  $query->entityCondition('entity_type', 'node')
    ->entityCondition('bundle', 'announcements')
    ->propertyCondition('status', 1)
    ->fieldOrderBy('field_announcement_date','value','DESC')
    ->propertyOrderBy('title','ASC');
  if ($count) {
    $query->range(0,$count);
  }
  $result = $query->execute();
  $announcements = array('nodes' => array());
  if (isset($result['node'])) {
    $announcement_nids = array_keys($result['node']);
    $announcements = array('nodes'=>entity_load('node', $announcement_nids));
  }
  else {
    return false;
  }
  return $announcements;
}



/* entityquery for letter nodes */

function sidebar_get_letters($count = FALSE) {
  $query = new EntityFieldQuery();
  $query->entityCondition('entity_type', 'node')
    ->entityCondition('bundle', 'letter')
    ->propertyCondition('status', 1)
    ->fieldOrderBy('field_letter_date','value','DESC')
    ->propertyOrderBy('title','ASC');
  if ($count) {
    $query->range(0,$count);
  }
  $result = $query->execute();
  $letters = array('nodes' => array());
  if (isset($result['node'])) {
    $letter_nids = array_keys($result['node']);
    $letters = array('nodes'=>entity_load('node', $letter_nids));
  }
  else {
    return false;
  }
  return $letters;
}



/* entityquery for newsletter nodes */

function sidebar_get_newsletters($count = FALSE) {
  $query = new EntityFieldQuery();
  $query->entityCondition('entity_type', 'node')
    ->entityCondition('bundle', 'newsletter')
    ->propertyCondition('status', 1)
    ->fieldOrderBy('field_newsletter_date','value','DESC')
    ->propertyOrderBy('title','ASC');
  if ($count) {
    $query->range(0,$count);
  }
  $result = $query->execute();
  $newsletters = array('nodes' => array());
  if (isset($result['node'])) {
    $newsletter_nids = array_keys($result['node']);
    $newsletters = array('nodes'=>entity_load('node', $newsletter_nids));
  }
  else {
    return false;
  }
  return $newsletters;
}

/* entityquery for upcoming calendars nodes */

function sidebar_get_sermon() {
  $query = new EntityFieldQuery();
  $query->entityCondition('entity_type', 'node')
    ->entityCondition('bundle', 'sermon')
    ->propertyCondition('status', 1)
    ->fieldOrderBy('field_sermon_date','value','DESC')
    ->propertyOrderBy('title','ASC')
    ->range(0,1);
  $result = $query->execute();
  $sermons = array('nodes' => array());
  if (isset($result['node'])) {
    $sermon_nids = array_keys($result['node']);
    $sermons = array('nodes'=>entity_load('node', $sermon_nids));
  }
  else {
    return false;
  }
  return $sermons;
}



/****************************
Implementation of hook_theme()
****************************/

function sidebar_theme() {
  return array(
    'sidebar_map' => array(
      'variables' => array('address'=>NULL,'external_url'=>NULL),
      'template' => 'theme/sidebar-map',
    ),
    'sidebar_welcome' => array(
      'variables' => array('calendars'=>NULL),
      'template' => 'theme/sidebar-welcome',
    ),
    'sidebar_upcoming_events' => array(
      'variables' => array('events'=>NULL),
      'template' => 'theme/sidebar-events',
    ),
    'sidebar_upcoming_events_page' => array(
      'variables' => array('events'=>NULL),
      'template' => 'theme/sidebar-events-page',
    ),
  );
}

